name: RunTests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
      test: true

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx jest --forceExit
